[tools]
bun = "latest"
"cargo:aviutl2-cli" = "latest"
"github:EmbarkStudios/cargo-about" = "latest"
"cargo:cargo-edit" = "latest"
node = "24"
ruby = "4"
"npm:rulesync" = "latest"
"cargo:hk" = "latest"
pkl = "latest"
