name: Setup Environment
description: 環境をセットアップする

runs:
  using: "composite"
  steps:
    - name: Set up Rust
      shell: bash
      run: |
        rustup toolchain install --profile minimal
        rustup component add clippy
        rustup component add rustfmt

    - name: Set up cargo-binstall
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-binstall

    - name: Cache rust
      uses: Swatinem/rust-cache@v2

    - name: Set up mise
      uses: jdx/mise-action@v3
      with:
        install: true
        experimental: true

    - name: Set up Ruby
      shell: bash
      run: |
        cmd /c "tree /F 'C:/Users/runneradmin/AppData/Local/mise/installs/ruby/4.0.1'"
        ridk install
        ridk enable
        bundle install
