[package]
name = "example-binaural-filter"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
publish = false

[lib]
name = "rusty_binaural_filter"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.104"
aviutl2.workspace = true
hrtf = "0.9.0"
itertools = "0.15.0"
lru = "0.18.3"
num-integer = "0.1.47"
ringbuffer = "0.16.0"

[build-dependencies]
anyhow = "1.0.104"
fs-err = "3.3.1"
ureq = "3.4.0"
